version: "3"
services:
  service1:
    build: ../Services/back
    container_name: back_container
    image: mon_image_fastapi:latest

    ports:
      - "8001:8001"

  service2:
    build: ../Services/front
    container_name: front_container
    image: mon_image_front:latest

    ports:
      - "8000:8000"

  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 5433

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data:
